services:
- type: web
  name: tempmail-qzz
  runtime: node
  plan: free
  buildCommand: npm install --omit=dev
  startCommand: npm start
  envVars:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: 3000
